### ISSUE TITLE
set the history file and size

### ISSUE THREAD

**Issue by AntPeixe** [zap-zsh/supercharge#6]
given that it's setting `APPEND_HISTORY` then I'd suggest that the following is also added so that it can actually be used and shared across terminals

```
SAVEHIST=1000
HISTFILE=$HOME/.zsh_history
```

And, in addition, I feel like the following are also beneficial
```
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_ignore_space
setopt share_history
```

**Comment by mamaraddio** [comment]
Done 👍
